[font]
  size = 10.0

[colors.primary]
  # TODO: this isn't working because colors.primary is defined on alacritty.toml.
  foreground = "#d9d9d9"
  background = "#012B36"
  bright_foreground = "#95a0a0"

