#!/bin/bash
#
# Script to test dunstrc config changes.

# close any running dunst processes
pidof dunst && killall dunst

# start dunst in the background
dunst &

notify-send -u low      msg1 "urgency low"
notify-send -u low      msg1 "urgency low" 
notify-send -u low      msg1 "urgency low"
notify-send -u normal   -i folder-new msg2 "urgency normal"
notify-send -u critical msg3 "urgency critical"
